services:
  redis_bot:
    env_file:
      - .env.local
    image: redis:7.0.5-alpine
    restart: always
    container_name: redis
    command: redis-server --requirepass ${REDIS_BOT_PASSWORD} --save 20 1

    volumes:
        - redis_bot_data:/data
    ports:
        - "${REDIS_BOT_PORT}:6379"
    networks:
      - bot-network

  db_bot:
    env_file:
      - .env.local
    image: postgres:15.1-alpine
    restart: always
    container_name: pg_db
    volumes:
      - db_bot_data:/opt/app/data
    ports:
      - "${DB_BOT_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_BOT_USER}
      - POSTGRES_PASSWORD=${DB_BOT_PASSWORD}
      - POSTGRES_DB=${DB_BOT_NAME}
    networks:
      - bot-network

  rabbitmq_bot:
    env_file:
      - .env.local
    restart: always
    image: rabbitmq:management
    container_name: rabbitmq_bot
    ports:
      - ${RABBITMQ_BOT_PORT}:5672
      - 15672:15672
    volumes:
      - rabbitmq_bot_data:/var/lib/rabbitmq
    networks:
      - bot-network

volumes:
  db_bot_data:
  redis_bot_data:
  rabbitmq_bot_data:

networks:
  bot-network:
    driver: bridge